### ISSUE TITLE
issues flashing MX25U51245GZ4I00

### ISSUE THREAD

**Issue by wesk1** [BrianPugh/game-and-watch-patch#41]
Hello,

Im trying to flash a MX25U51245GZ4I00, but its not working.

i used the following cmds

# in this repo
make clean
make PATCH_PARAMS="--device=zelda" flash_patched

# in the retro-go repo
make clean
# In this example, I'm assuming you have a 64MB flash chip (60 = 64 - 4)
make -j8 EXTFLASH_SIZE_MB=60 EXTFLASH_OFFSET=4194304 INTFLASH_BANK=2 flash

im not sure if i need to modify the make file before running cmd, i do get to the erase part but when it tries to do the next step i goes to another screen….see attachment, at first i kept getting cannot communicate with external flash, i reflowed the chip then the following message started to appear. 

thanks in advance 
 
![D0B36B2B-6C5C-4601-B237-7AE06211345B](https://user-images.githubusercontent.com/518983/146312641-96889ce6-11c1-4e77-b401-2eb41846ae29.jpeg)

**Comment by BrianPugh** [comment]
I'm not 100% sure, but you might have a bad connection to your chip. You might find more interactive help in the stacksmashing discord. If you do find the issue, please post back here you solution!

**Comment by wesk1** [comment]
I grabbed a new chip, used lead solder this time it looks like its working, flashing ok in retro.
