### ISSUE TITLE
Patch OG Firmware to support MX25U51245GZ4I54

### ISSUE THREAD

**Issue by drandreas** [BrianPugh/game-and-watch-patch#42]
MX25U51245GZ4I54 difers to the MX25U51245GZ4I00 in the number of dummy cycles that must be inserted for READ operations (always 10 instead of between 6 to 8 depending on the frequency) and the addressing mode (it is always 32bit).

Tim had added the required patches to his software for the Mario G&W. Firmware Patcher but then discontinued the development. I was hoping you would be willing to "port" the support for special Flash chips to the Zelda G&W. I did diff his changes back in spring. What I know so far is that he patches/replaces 5 functions of original firmware: 

- Flash Init, called from:
  - 0x080061a4
  - 0x08006378
- SPI Command, called from:
  - 0x08007422  
  - 0x0800749a
  - 0x0800751a
  - 0x0800759c
  - 0x08007604
  - 0x08007684
  - 0x08007762
  - 0x080077d0
  - 0x08007852
  - 0x08007888
- Read Flash Status Register, called from:
  - 0x08004f98
  - 0x08004ff6
- Write Flash Status Register, called from:
  - 0x08004fd8
- Reset Flash, called from:
  - 0x08004828

**Comment by drandreas** [comment]
The patch you have linked above patches the original firmware to work with one specific Flash type. I was striving for a more universal solution. Since it might also help others with strange Flash chips. In the meantime, I've dug deeper in into your code. If my understanding is correct the calls from my initial post would roughly translate into the following `mario.py`:

```python
self.internal.replace(0x080061a4, "OSPI_Init")
self.internal.replace(0x08006378, "OSPI_Init")

self.internal.replace(0x08007422, OSPI_Command")
self.internal.replace(0x0800749a, OSPI_Command")
self.internal.replace(0x0800751a, OSPI_Command")
self.internal.replace(0x0800759c, OSPI_Command")
self.internal.replace(0x08007604, OSPI_Command")
self.internal.replace(0x08007684, OSPI_Command")
self.internal.replace(0x08007762, OSPI_Command")
self.internal.replace(0x080077d0, OSPI_Command")
self.internal.replace(0x08007852, OSPI_Command")
self.internal.replace(0x08007888, OSPI_Command")

self.internal.replace(0x08004f98, "read_flash_reg")
self.internal.replace(0x08004ff6, "read_flash_reg")

self.internal.replace(0x08004fd8, "write_flash_reg")

self.internal.replace(0x08004828, "reset_flash")
```

The majority of the code could be copied over from https://github.com/kbeckmann/game-and-watch-retro-go/blob/main/Core/Src/gw_flash.c and then padded with some glue code to translate the original API calls.

By the way have you considered using `__attribute__((used))` in the function declaration instead of `--undefined=` in the Makefile?

**Comment by BrianPugh** [comment]
it would be something like that (except remove the leading `0x0800` from the address, the first parameter is just the offset into the binary).

As for using `__attribute__((used))`, I'll check that out, i like that much better.

As for getting this working, I guess all I can offer is help through here/discord, but i can't directly test/debug anything since I don't have that chip.

**Comment by BrianPugh** [comment]
I couldn't get `__attribute__((used))` to work, but i only tried on the `bootloader` function.

**Comment by drandreas** [comment]
Yes `__attribute__((used))` does not work in this setup - strange.

Returning to the initial topic. I will try to add the hooks as described above over the weekend and report back how it goes.

**Comment by drandreas** [comment]
I managed to patch most of the function calls I had identified earlier (https://github.com/drandreas/game-and-watch-patch, note the actual implementation is not done yet). However, my initial understanding of what `replace` does was wrong. The correct python method calls are `self.internal.bl` and `self.internal.b`. Sadly the latter does not like string arguments. Yes, it’s strange use for `b`. My best guess is, that the compiler uses this trick to optimise overloaded method calls.

Below you find the disassembly of the section where I would like to patch a branch (without link): ![b](https://user-images.githubusercontent.com/8958160/147851270-7d440a0c-10ea-499a-ae35-22e759da5de4.png)

Could you extend b to also support function names, without breaking the rest?

**Comment by BrianPugh** [comment]
so looking back through my code right now. I don't believe I added the address-lookup-from-string because the thumb branch command is limited to a 2048 max-relative-distance jump, which makes it very limiting. For example, you couldn't reach code at the end of the binary from offset 0x7744. Perhaps it might be better to intercept the call at another location.

**Comment by drandreas** [comment]
I double checked that in my trusted ARM Assembly Manual. You are absolutely right. I'n that case I will follow the call chain and find alternatives.

**Comment by drandreas** [comment]
I'm making slow progress. I'will open a merge request as soon as I have something to show.

**Comment by drandreas** [comment]
> so looking back through my code right now. I don't believe I added the address-lookup-from-string because the thumb branch command is limited to a 2048 max-relative-distance jump, which makes it very limiting. For example, you couldn't reach code at the end of the binary from offset 0x7744. Perhaps it might be better to intercept the call at another location.

The disassembly wasn't precise enough. The op-code is in fact 32-bit. I've now implemented `b.w` (see: https://github.com/drandreas/game-and-watch-patch/commit/09cf280bb03263ccc30b9380477b28da03fccb2c
) for the 2 branch instructions discussed earlier `b.w` T4 differs by one bit from `bl` T2 which is also 32-bit.

**Comment by BrianPugh** [comment]
looks nice! lookin forward to the PR
