### ISSUE TITLE
 MX66U1G

### ISSUE THREAD

**Issue by apple524** [BrianPugh/game-and-watch-patch#43]
Info : clock speed 1800 kHz
Info : STLINK V2J34S7 (API v2) VID:PID 0483:3748
Info : Target voltage: 3.164698
Info : stm32h7x.cpu0: Cortex-M7 r1p1 processor detected
Info : stm32h7x.cpu0: target has 8 breakpoints, 4 watchpoints
Info : starting gdb server for stm32h7x.cpu0 on 3333
Info : Listening on port 3333 for gdb connections
Info : Device: STM32H7Ax/7Bx
Info : flash size probed value 128k
Info : STM32H7 flash has dual banks
Info : Bank (0) size is 256 kb, base address is 0x08000000
Initializing Octo-SPI interface
Error: Target not halted
Error: Timeout while polling BUSY
Error executing event reset-end on target stm32h7x.cpu0:
embedded:startup.tcl:854: Error:
in procedure 'ocd_process_reset'
in procedure 'ocd_process_reset_inner' called at file "embedded:startup.tcl", line 854
make[1]:  “/home/gw/opt/game-and-watch-patch”
gw@gw-virtual-machine:~/opt/game-and-watch-patch$  Target not halted executing event reset-end on target stm32h7x.cpu0:Info : flash1 'sfdp' id = 0x3b25c2 size = 131072kbytesTimeout while polling BUSY

**Comment by BrianPugh** [comment]
check your connections, or maybe its pressing the power button at the correct time. The Target voltage looks incorrect.

**Comment by drandreas** [comment]
@apple524 please post the suffix of your chips part number is it G54 or G100 ?

**Comment by apple524** [comment]
> @apple524 please post the suffix of your chips part number is it 54 or 00 ?

MX66U1G45G 
NJ00H
