### ISSUE TITLE
Raspberry 3 cant compile ?!

### ISSUE THREAD

**Issue by gmcpaul** [BrianPugh/game-and-watch-patch#48]
Hi, 
Having trouble to compile the image according to the manual.

basically it fails during install of the keystone-engine package.
also maybe a point was to extende the swap which froze the pi at 43% during keystone engine compile.

pip3 install -r requirements.txt
>>  keystone-engine-0.9.2.tar.gz 
output is 

      -- Generating done
      -- Build files have been written to: /tmp/pip-install-9fldl7ig/keystone-engine_aec0dce891ea4b8b811b9b772471acf2/src/build
      [ 67%] Built target keystone
      [ 68%] Built target fuzz_asm_ppc32be
      [ 70%] Built target fuzz_asm_mips
      [ 71%] Built target fuzz_asm_arm_thumb
      [ 73%] Built target fuzz_asm_mips64
      [ 73%] Built target fuzz_asm_hex
      [ 77%] Built target fuzz_asm_arm_thumbv8be
      [ 77%] Built target fuzz_asm_armv8_arm
      [ 77%] Built target fuzz_asm_arm_thumbv8
      [ 78%] Built target fuzz_asm_systemz
      [ 79%] Built target fuzz_asm_x86_64
      [ 80%] Built target fuzz_asm_arm_armv8be
      [ 81%] Built target fuzz_asm_evm
      [ 82%] Built target fuzz_asm_x86_16
      [ 83%] Built target fuzz_asm_arm_arm
      [ 85%] Built target fuzz_asm_x86_32
      [ 87%] Built target fuzz_asm_arm_thumbbe
      [ 88%] Built target fuzz_asm_arm64_arm
      [ 89%] Built target fuzz_asm_ppc64
      [ 91%] Built target fuzz_asm_ppc64be
      [ 93%] Built target fuzz_asm_mipsbe
      [ 94%] Built target fuzz_asm_mips64be
      [ 96%] Built target fuzz_asm_sparcbe
      [ 97%] Built target fuzz_asm_sparc
      [ 98%] Built target fuzz_asm_sparc64be
      [100%] Built target fuzz_asm_arm_armbe
      error: [Errno 2] No such file or directory: '/tmp/pip-install-9fldl7ig/keystone-engine_aec0dce891ea4b8b811b9b772471acf2/src/build/llvm/lib64/libkeystone.so'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> keystone-engine

OS Rasbian 32bit release from 22.9.22
any hints?

**Comment by PolluxPT** [comment]
Try this:

«««« Keystone-engine Workaround: »»»»

wget https://files.pythonhosted.org/packages/0a/65/3a2e7e55cc1db188869bbbacee60036828330e0ce57fc5f05a3167ab4b4d/keystone-engine-0.9.2.tar.gz

tar -zxvf keystone-engine-0.9.2.tar.gz

tar czvf keystone-engine-0.9.2mod.tar.gz keystone-engine-0.9.2

pip install keystone-engine-0.9.2mod.tar.gz


»»»» Edit line 114 in setup.py: 

**obj_dir = os.path.join(BUILD_DIR, 'llvm', 'lib', 'arm-linux-gnueabihf')**

**Comment by gmcpaul** [comment]
worked !
thanks a lot!!
