### ISSUE TITLE
最新更新的版本有系统bug

### ISSUE THREAD

**Issue by hexiaotun** [BrianPugh/game-and-watch-patch#51]
最新更新的双系统刷进去后最后显示
Info : clock speed 1800 kHz
Info : STLINK V2J17S4 (API v2) VID:PID 0483:3748
Info : Target voltage: 2.757715
Info : [stm32h7x.cpu0] Cortex-M7 r1p1 processor detected
Info : [stm32h7x.cpu0] target has 8 breakpoints, 4 watchpoints
Error executing event examine-end on target stm32h7x.cpu0:
read_memory: failed to read memory
Info : starting gdb server for stm32h7x.cpu0 on 3333
Info : Listening on port 3333 for gdb connections
Warn : target was in unknown state when halt was requested
Info : Halt timed out, wake up GDB.
Error: timed out while waiting for target halted

然后机器是黑屏不能开机，任何按钮都没反应。重置电池后乍眼看好像是能用，实际按game+Right会死机，按任何按钮都不能重置，只能重新重置电池，用旧版本就没问题。

**Comment by BrianPugh** [comment]
Google Translating:

> The latest update of the dual system is finally displayed after flashing in
Info : clock speed 1800 kHz
Info : STLINK V2J17S4 (API v2) VID:PID 0483:3748
Info : Target voltage: 2.757715
Info : [stm32h7x.cpu0] Cortex-M7 r1p1 processor detected
Info : [stm32h7x.cpu0] target has 8 breakpoints, 4 watchpoints
Error executing event examine-end on target stm32h7x.cpu0:
read_memory: failed to read memory
Info : starting gdb server for stm32h7x.cpu0 on 3333
Info : Listening on port 3333 for gdb connections
Warn : target was in unknown state when halt was requested
Info : Halt timed out, wake up GDB.
Error: timed out while waiting for target halted

> Then the machine is a black screen and cannot be turned on, and any button does not respond. After resetting the battery, it seems that it can be used at first glance, but actually pressing game+Right will freeze the machine, and pressing any button will not reset it, only reset the battery again, and the old version will be fine.

This is a bad side-effect from me adding triple-boot support. I will disable this by default; just a moment!

**Comment by BrianPugh** [comment]
Fixed in #52 and released in v0.6.

**Comment by hexiaotun** [comment]
> Fixed in #52 and released in v0.6.
感谢！
