### ISSUE TITLE
gw_retro_go.elf section doesn't fit using Zelda documentation - Stock 4MB Flash Chip

### ISSUE THREAD

**Issue by gigaclood** [BrianPugh/game-and-watch-patch#53]
Hi, 
I installed game-and-watch-noob-installer to patch my Game and Watch Zelda (Stock).

All steps under backup (also restore) go fine.
Also step:
`   make PATCH_PARAMS="--device=zelda --no-la --no-sleep-images" flash`
goes fine (and I saw that Link's Awakening from start menu didn't work as I expected)

Using
`make -j8 INTFLASH_BANK=2 EXTFLASH_SIZE=1794336 EXTFLASH_OFFSET=860160 ADAPTER=stlink GNW_TARGET=zelda flash`

I obtain

`/opt/gcc-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: build/gw_retro_go.elf section `._saveflash' will not fit in region `SAVEFLASH'
/opt/gcc-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: build/gw_retro_go.elf section `._fbflash' will not fit in region `FBFLASH'
/opt/gcc-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: region `SAVEFLASH' overflowed by 3808 bytes
/opt/gcc-arm-none-eabi/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: region `FBFLASH' overflowed by 3808 bytes`

If you are interested I'm using windows with WSL2 and STLink2 Clone (connected to wsl2 using usbipd.exe)

**Comment by BrianPugh** [comment]
I'd recommend trying to get Zelda3 working first, then dual/triple boot. The error you're currently seeing is due to using gcc 10.2.1 instead of a more modern version (12.2.1). Checkout the stacksmashing discord server (#homebrew channel) or open up an issue in the marian-m12l/game-and-watch-zelda3 repo

**Comment by gigaclood** [comment]
Thank you!
I'll try to update GCC on WSL.
Just to inform: I'm not flash zelda3, only dual boot with retro game

**Comment by BrianPugh** [comment]
Oh gotcha! In that case, you may have too many ROMs or something.

**Comment by Takiiiiiiii** [comment]
FYI, this error happens even with a single Tetris ROM (49KB uncompressed). Something is wrong with the make instructions, or it isn't possible to dual boot on a 4MB Zelda using current repo versions.
