### ISSUE TITLE
RIGHT+GAME return

### ISSUE THREAD

**Issue by igaspaly4** [BrianPugh/game-and-watch-patch#55]
I pressed RIGHT+GAME, the console turned off. How do I turn it back on without taking the console apart?

**Comment by BrianPugh** [comment]
do you have the programming pins exposed? if so you can hook it up and run `make reset`. This bug was recently introduced in v0.5 and fixed in v0.6, apologies for the inconvenience!

**Comment by igaspaly4** [comment]
Yes, the contacts are out, thanks for the tip.
In version 0.6, if you do not write --triple-boot when patching, will the combination r+g work?

**Comment by BrianPugh** [comment]
>In version 0.6, if you do not write --triple-boot when patching, will the combination r+g work?

If the flag `--triple-boot` is **not** provided, then right+game will perform no action (and not softlock your system).

**Comment by igaspaly4** [comment]
Thanks, everything works on the 0.6 version!
