### ISSUE TITLE
[ZELDA] GB games resets retro-go config (and sometimes BSOD)

### ISSUE THREAD

**Issue by DSkywalk** [BrianPugh/game-and-watch-patch#59]
Hello @BrianPugh, I'm experimenting to take a little more advantage of the stock zelda, I hope you still have the disassembly at hand :dancers: 

I have seen that if you run GB zeldas several times, changing the language, running and resetting the game. It deletes a code area supposedly available. We should not allow to run the gameboy emulator, to avoid problems if `--no-la` is used.

Sometimes its corrupt the retro-go config and when you load any rom... BSODs :boom: 

![imagen](https://github.com/BrianPugh/game-and-watch-patch/assets/560310/fbcadafd-4fcb-401b-a9e8-453acf269ce3)

If you tell me some NOP to avoid it I'll upload it as PR.

Thanks for your great work :+1:

**Comment by BrianPugh** [comment]
I'm not sure if I have the ghidra files still laying around; I'd also be a little hesitant to share them (to be sure that no proprietary code leaks).

That said, a lot of my notes (and commented out code of stuff i was working on) is in the [zelda file](https://github.com/BrianPugh/game-and-watch-patch/blob/main/patches/zelda.py).

As for fixing the presented issue, I'm open to PRs. I might be able to get around to it at some point, but unfortunately it's not very high on my priority list (I've got a lot of projects/work going on atm).

**Comment by DSkywalk** [comment]
I wasn't commenting to share them, but just in case you could look at the menu area and prevent the 3rd option of the zelda menu from being able to be executed.

**Comment by BenjaminSoelberg** [comment]
I'll give it a go.

**Comment by BenjaminSoelberg** [comment]
I have a solution, and I'll push a PR soon. @DSkywalk would you be so kind and do you have the time to help me test it ?

**Comment by BrianPugh** [comment]
thanks @BenjaminSoelberg for the PR! Love it!

Closing this issue.

**Comment by DSkywalk** [comment]
really thanks @BenjaminSoelberg :heart:
