### ISSUE TITLE
--watchonly feature suggestion

### ISSUE THREAD

**Issue by damonmo** [BrianPugh/game-and-watch-patch#6]
First of all many thanks for your awesome work on this project! In case you want to keep pushing it further, one feature that I personally would love to see is having something like a --watchonly option that strips SMB1, SMB2 & Ball and only leaves the watch, so that when you press GAME it would jump directly into Retro-go (as SMB1, SMB2 & original Ball can run emulated anyway).

**Comment by BrianPugh** [comment]
Sure i can definitely work on that; it's actually how I use it! I can definitely strip SMB2 (will save 42,917 bytes), but I cannot strip SMB1 as the clock heavily depends on it. I'll have to do a little more digging to see how Ball is hooked up, so that's a maybe.

**Comment by BrianPugh** [comment]
Initial feature now available from https://github.com/BrianPugh/game-and-watch-patch/pull/9 . I'll continue working on space savings, but the infrastructure is all there now.
