### ISSUE TITLE
Dual stock firmware (Zelda+Mario) in a single device.

### ISSUE THREAD

**Issue by rutdarkronin** [BrianPugh/game-and-watch-patch#70]
Hello! Thank you for your hard work, this project is really magnificent!
One question though. Could we have triple-firmware (Zelda+Mario+RetroGo) working in a single Zelda device assuming that SPI is changed to something bigger? I tried to flash Mario internal-only binary to both 8020000 (second 128kb of bank1) or bank2 - it just gives black screen when switching with Game+</>, so I assuming some patching needs to be done.
Please let me know if this is possible somehow, thanks!

**Comment by BrianPugh** [comment]
Currently this repo doesn't support that, but of course nothing is impossible 😁.

Unfortunately it would take a lot of work that I'm not particularly interested in.

**Comment by rutdarkronin** [comment]
Thank you!
Maybe someday...)
